name: 'Upload Thunderstore Package TEST'
description: 'Formats and uploads a Thunderstore package'
author: 'AnActualEmerald'
branding:
  icon: 'package'
  color: 'green'
inputs:
  path: 
    descritpion: 'Path to the files of the mod. Uses the contents of the repo if not set'
  community:
    description: 'Thunderstore community to publish to'
    required: true
  namespace:
    description: 'Name of the team to publish the mod under'
    required: true
  name:
    description: 'Name of the package'
    required: true
  version:
    description: 'Package version to publish'
    required: true
  icon:
    description: 'URL of the mod icon'
  readme:
    description: 'URL of the mod README'
  changelog:
    description: 'URL of the mod CHANGELOG'
  description:
    description: 'Description of the mod'
    required: true
    default: 'Example mod description'
  token:
    description: 'Thunderstore API token'
    required: true
  dev:
    description: 'Push to thunderstore.dev rather then thunderstore.io'
  wrap:
    description: 'Directory to wrap the contents of the repo in'
  website:
    description: 'Homepage URL'
  categories:
    description: 'Categories the mod belongs to'
  deps: 
    description: 'List of dependencies by name & version'
  nsfw:
    description: 'Is the mod NSFW'
  file:
    description: 'Prebuilt .zip file to use, relative to the repo root'
  repo:
    description: 'The URL of the thundertore repo to publish to'
outputs:
  url:
    description: 'URL of uploaded mod'
runs:
  using: docker
  image: 'Dockerfile'
  env: 
    TCLI_AUTH_TOKEN: ${{ inputs.token }}
    TS_COMMUNITY: ${{ inputs.community }}
    TS_NAMESPACE: ${{ inputs.namespace }}
    TS_NAME: ${{ inputs.name }}
    TS_VERSION: ${{ inputs.version }}
    TS_DESC: ${{ inputs.description }}
    TS_ICON: ${{ inputs.icon }}
    TS_README: ${{ inputs.readme }}
    TS_CHANGELOG: ${{ inputs.changelog }}
    TS_PATH: ${{ inputs.path }}
    TS_DEV: ${{ inputs.dev }}
    TS_WRAP: ${{ inputs.wrap }}
    TS_WEBSITE: ${{ inputs.website }}
    TS_CATEGORIES: ${{ inputs.categories }}
    TS_DEPS: ${{ inputs.deps }}
    TS_NSFW: ${{ inputs.nsfw }}
    TS_FILE: ${{ inputs.file }}
    TS_REPO: ${{ inputs.repo }}
