name: 'Upload Thunderstore Package'
description: 'Formats and uploads a Thunderstore package'
inputs:
  path: 
    descritpion: 'Path to the files of the mod. Uses the contents of the repo if not set'
  community:
    description: 'Thunderstore community to publish to'
    required: true
  namespace:
    description: 'Name of the team to publish the mod under'
    required: true
  name:
    description: 'Name of the package'
    required: true
  version:
    description: 'Package version to publish'
    required: true
  icon:
    description: 'URL of the mod icon'
  readme:
    description: 'URL of the mod README'
  description:
    description: 'Description of the mod'
    required: true
    default: 'Example mod description'
  token:
    description: 'Thunderstore API token'
    required: true
  dev:
    description: 'Push to thunderstore.dev rather then thunderstore.io'
outputs:
  url:
    description: 'URL of uploaded mod'
runs:
  using: docker
  image: Dockerfile
  env: 
    TS_TOKEN: ${{ inputs.token }}
    TS_COMMUNITY: ${{ inputs.community }}
    TS_NAMESPACE: ${{ inputs.namespace }}
    TS_NAME: ${{ inputs.name }}
    TS_VERSION: ${{ inputs.version }}
    TS_DESC: ${{ inputs.description }}
    TS_ICON: ${{ inputs.icon }}
    TS_README: ${{ input.readme }}
    TS_PATH: ${{ inputs.path }}
    TS_DEV: ${{ inputs.dev }}
